name: MMOInventoryPlaceholder
version: '${project.version}'
main: com.github.e2318501.mmoinventoryplaceholder.MMOInventoryPlaceholder
api-version: '1.19'
depend: [ PlaceholderAPI ]
softdepend: [ MMOInventory ]
